# ------------------------------------------------------------------------------
# Archivo: .pre-commit-config.yaml
# Configuración alineada con prácticas recomendadas de CI/CD.
# Herramientas integradas: Black, isort, Ruff, mypy y pytest
# ------------------------------------------------------------------------------

default_language_version:
  python: python3.9

repos:
  # ----------------------------------------------------------------------------
  # Hooks estándar recomendados por pre-commit.
  # ----------------------------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: detect-private-key
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict

# ------------------------------------------------------------------------------
# Limpieza automática de metadata de notebooks Jupyter.
# ------------------------------------------------------------------------------
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout

# ------------------------------------------------------------------------------
# Formateador de código Python: Black
# ------------------------------------------------------------------------------
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.9
      - id: black-jupyter
        args: ["--safe"]
        language_version: python3.9

# ------------------------------------------------------------------------------
# Ordenar automáticamente imports: isort
# ------------------------------------------------------------------------------
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

# ------------------------------------------------------------------------------
# Linting con Ruff, alineado con prácticas estándar de CI.
# ------------------------------------------------------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: ["check", "--fix", "--exit-zero"]

# ------------------------------------------------------------------------------
# Verificación estática de tipos: mypy
# ------------------------------------------------------------------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]

# ------------------------------------------------------------------------------
# Ejecución de tests unitarios antes de commits: pytest
# ------------------------------------------------------------------------------
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false

# ------------------------------------------------------------------------------
# Exclusiones globales
# ------------------------------------------------------------------------------
exclude: |
  (?x)^(
    \.pytest_cache|
    \.ruff_cache|
    legacy|
    build|
    dist|
    \.eggs|
    \.git|
    \.github|
    __pycache__|
    model\.json
  )
