name: 'Continuous Delivery'

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and Push Docker image
        run: |
          # Configure Docker to use gcloud as a credential helper
          gcloud auth configure-docker

          # Build the Docker image
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flight-delay-api:${{ github.sha }} .

          # Push the Docker image to Google Container Registry
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flight-delay-api:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flight-delay-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flight-delay-api:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --memory 1Gi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 10

      - name: Get service URL
        id: get-url
        run: |
          SERVICE_URL=$(gcloud run services describe flight-delay-api --platform managed --region us-central1 --format='value(status.url)')
          echo "service_url=$SERVICE_URL" >> $GITHUB_OUTPUT
          # Replace the STRESS_URL variable in the Makefile
          sed -i "s|^STRESS_URL = .*|STRESS_URL = $SERVICE_URL|g" Makefile

      # New step to install Python dependencies
      - name: Install Dependencies for Stress Test
        run: |
          python -m pip install --upgrade pip
          # Install requirements-test.txt (includes locust)
          pip install -r requirements-test.txt
          # And/or if your tests also need main requirements:
          # pip install -r requirements.txt

      - name: Run stress tests
        run: make stress-test
